name: Build LaTeX to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build HTML/PDF with Pandoc (Docker)
        uses: addnab/docker-run-action@v3
        with:
          image: pandoc/latex:latest
          options: -v ${{ github.workspace }}:/data
          run: |
            set -eu
            cd /data

            BUILD_DIR=_build
            ARTIFACT_DIR=_public
            rm -rf "$BUILD_DIR" "$ARTIFACT_DIR"
            mkdir -p "$BUILD_DIR" "$ARTIFACT_DIR"
            cp -f styles.css "$ARTIFACT_DIR/" || true

            # For each course (*/src)
            for d in */src ; do
              [ -d "$d" ] || continue
              course="${d%/src}"
              echo "Building course: $course"

              mkdir -p "$course/site" "$BUILD_DIR/$course"
              cp -f styles.css "$course/site/" || true

              # 1) Preprocess .tex: map tcolorbox -> quote (keeps content in HTML)
              for f in "$d"/*.tex ; do
                [ -e "$f" ] || continue
                base="$(basename "$f")"
                sed -e 's/\\begin{tcolorbox}/\\begin{quote}/g' \
                    -e 's/\\end{tcolorbox}/\\end{quote}/g' \
                  "$f" > "$BUILD_DIR/$course/$base"
              done

              # 2) Build each preprocessed .tex (so \input{} also uses processed files)
              for f in "$BUILD_DIR/$course"/*.tex ; do
                [ -e "$f" ] || continue
                base="$(basename "$f" .tex)"
                echo "  - $f -> $course/site/${base}.html"
                pandoc "$f" \
                  --from=latex \
                  --to=html5 \
                  --mathjax \
                  --template /data/_template.html \
                  --resource-path="$BUILD_DIR/$course" \
                  --toc --number-sections \
                  -o "$course/site/${base}.html"
                pandoc "$f" -o "$course/site/${base}.pdf" || true
              done

              # 3) Course index: prefer main.tex if present
              if [ -f "$BUILD_DIR/$course/main.tex" ]; then
                pandoc "$BUILD_DIR/$course/main.tex" \
                  --from=latex --to=html5 --mathjax \
                  --template /data/_template.html \
                  --resource-path="$BUILD_DIR/$course" \
                  --toc --number-sections \
                  -o "$course/site/index.html"
              else
                {
                  printf '%s\n' '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'"$course"'</title><link rel="stylesheet" href="styles.css"></head><body>'
                  printf '%s\n' '<h1>'"$course"'</h1><ul>'
                  for h in "$course/site/"*.html ; do
                    [ -e "$h" ] || continue
                    file="$(basename "$h")"
                    [ "$file" = "index.html" ] && continue
                    name="${file%.html}"
                    printf '<li><a href="%s">%s</a> (<a href="%s.pdf">pdf</a>)</li>\n' "$file" "$name" "$name"
                  done
                  printf '%s\n' '</ul></body></html>'
                } > "$course/site/index.html"
              fi

              # 4) Copy course site to artifact
              mkdir -p "$ARTIFACT_DIR/$course"
              cp -R "$course/site/." "$ARTIFACT_DIR/$course/"
            done

            # Root landing page
            {
              printf '%s\n' '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notes</title><link rel="stylesheet" href="styles.css"></head><body>'
              printf '%s\n' '<h1>Course Notes</h1><ul>'
              for c in "$ARTIFACT_DIR"/* ; do
                [ -d "$c" ] || continue
                name="$(basename "$c")"
                printf '<li><a href="%s/">%s</a></li>\n' "$name" "$name"
              done
              printf '%s\n' '</ul></body></html>'
            } > "$ARTIFACT_DIR/index.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

